/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

//import org.junit.jupiter.api.Test;

//import static org.junit.jupiter.api.Assertions.assertEquals;

class ValidatorTest {

}
