/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    //id("checkstyle")
}
group = "hexlet.code"
version = "1.0-SNAPSHOT"

dependencies {
    testImplementation("org.junit:junit-bom:5.9.1")
    testImplementation(platform("org.junit.jupiter:junit-jupiter"))
}

application {
    // Define the main class for the application.
    mainClass = "hexlet.code.App"
}
