/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    //id("checkstyle")
}
group = "hexlet.code"
version = "1.0-SNAPSHOT"
dependencies {
    // implementation("org.apache.commons:commons-text")
    // implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass = "hexlet.code.App"
}
